###
@createdAt = {{$datetime iso8601}}
###
POST http://localhost:3001/api/categories
Content-Type: application/json

{
    "title": "Pecho",
    "exercise": [{
        "name": "Press banca",
        "peso": 0,
          "repeticiones": 0,
          "series": 0
    },
    {
        "name": "Press incl. con mancuernas",
        "peso": 0,
          "repeticiones": 0,
          "series": 0
    }
    ],
    "createAt": "{{createdAt}}",
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu8qK5mNV_W1j823KeA_qfF8wFLdoihyIsaA&s"
}